keys:
  - &pascal age1u5vktt8749t3ztwyp8qup62ym3grcuzmlaa6fh7cwefhkhl7792snnukvw
  - &gaetan age16fjn06trywshgm5gg68d8zyr7x0tgdd2x22v92hrrtx806rq3sfs9xl5f6

creation_rules:
  - path_regex: hosts/pascal/secrets.yaml$
    key_groups:
    - age:
      - *pascal
      - *gaetan
