keys:
  - &ada age13z5mcpxjn3uhh4xm9r6y7fsaxurtjspwjhtmu08kgzm2xh9cgdcseq88he
  - &gaetan age16fjn06trywshgm5gg68d8zyr7x0tgdd2x22v92hrrtx806rq3sfs9xl5f6

creation_rules:
  - path_regex: hosts/ada/secrets.yaml$
    key_groups:
    - age:
      - *ada
      - *gaetan
